module.exports = [
  "Your inspiring energy makes people happy.",
  "Your caring empathy changes lives.",
  "Your creative passion is deeply appreciated.",
  "Your wonderful passion is unforgettable.",
  "Your strong presence is a gift.",
  "Your wonderful energy changes lives.",
  "Your unique passion is truly beautiful.",
  "Your bright presence matters so much.",
  "Your smart presence is so comforting.",
  "Your creative ideas brings joy to others.",
  "Your gentle perspective is a gift.",
  "Your sweet ideas inspires people.",
  "Your courageous empathy is a gift.",
  "Your funny laugh makes the world better.",
  "Your valued ideas is so comforting.",
  "Your kind spirit matters so much.",
  "Your brilliant smile is so comforting.",
  "Your kind spirit makes the world better.",
  "Your unique presence makes the world better.",
  "Your brave heart lights up the room.",
  "Your sweet energy inspires people.",
  "Your strong mind is unforgettable.",
  "Your thoughtful heart is unforgettable.",
  "Your special ideas makes people happy.",
  "Your brave spirit makes people happy.",
  "Your bright ideas changes lives.",
  "Your courageous smile changes lives.",
  "Your inspiring soul makes the world better.",
  "Your unique compassion is truly beautiful.",
  "Your fierce ideas makes people happy.",
  "Your loved mind makes people happy.",
  "Your brilliant laugh brings joy to others.",
  "Your sweet smile makes people happy.",
  "Your inspiring laugh lights up the room.",
  "Your wonderful smile makes the world better.",
  "Your beautiful spirit is truly beautiful.",
  "Your smart smile changes lives.",
  "Your beautiful empathy is truly beautiful.",
  "Your creative empathy matters so much.",
  "Your gentle empathy lights up the room.",
  "Your fierce spirit makes people happy.",
  "Your funny smile brings joy to others.",
  "Your beautiful heart inspires people.",
  "Your wonderful laugh is so comforting.",
  "Your gentle smile changes lives.",
  "Your funny smile makes people happy.",
  "Your sweet perspective is unforgettable.",
  "Your amazing smile is so comforting.",
  "Your funny perspective inspires people.",
  "Your precious smile makes the world better.",
  "Your brave compassion is unforgettable.",
  "Your smart passion brings joy to others.",
  "Your special empathy is unforgettable.",
  "Your warm perspective lights up the room.",
  "Your fierce laugh matters so much.",
  "Your loved empathy is unforgettable.",
  "Your amazing soul is so comforting.",
  "Your loved smile matters so much.",
  "Your unique passion makes people happy.",
  "Your caring spirit inspires people.",
  "Your special spirit brings joy to others.",
  "Your unique ideas is a gift.",
  "Your kind empathy makes people happy.",
  "Your warm passion changes lives.",
  "Your valued smile is so comforting.",
  "Your courageous spirit is unforgettable.",
  "Your inspiring soul brings joy to others.",
  "Your inspiring compassion changes lives.",
  "Your thoughtful heart lights up the room.",
  "Your brilliant spirit changes lives.",
  "Your special empathy is deeply appreciated.",
  "Your beautiful mind is deeply appreciated.",
  "Your precious smile is a gift.",
  "Your inspiring passion inspires people.",
  "Your loved laugh is so comforting.",
  "Your funny energy lights up the room.",
  "Your strong spirit is a gift.",
  "Your bright compassion changes lives.",
  "Your unique laugh is unforgettable.",
  "Your warm energy is so comforting.",
  "Your courageous empathy changes lives.",
  "Your funny compassion is truly beautiful.",
  "Your strong soul is unforgettable.",
  "Your sweet compassion makes people happy.",
  "Your fierce heart is so comforting.",
  "Your warm soul changes lives.",
  "Your inspiring passion makes the world better.",
  "Your resilient energy is a gift.",
  "Your amazing ideas is a gift.",
  "Your beautiful soul is truly beautiful.",
  "Your bright compassion is a gift.",
  "Your amazing energy is a gift.",
  "Your bright ideas inspires people.",
  "Your brave heart is truly beautiful.",
  "Your kind energy makes people happy.",
  "Your valued heart makes the world better.",
  "Your thoughtful perspective is truly beautiful.",
  "Your warm passion makes people happy.",
  "Your resilient passion is unforgettable.",
  "Your warm spirit brings joy to others.",
  "Your beautiful laugh is unforgettable.",
  "Your resilient ideas makes people happy.",
  "Your thoughtful compassion is unforgettable.",
  "Your beautiful perspective inspires people.",
  "Your inspiring energy makes the world better.",
  "Your smart energy is so comforting.",
  "Your funny compassion matters so much.",
  "Your fierce passion is unforgettable.",
  "Your kind passion changes lives.",
  "Your smart perspective matters so much.",
  "Your kind compassion is truly beautiful.",
  "Your brilliant perspective is unforgettable.",
  "Your amazing laugh is unforgettable.",
  "Your wonderful laugh changes lives.",
  "Your smart energy changes lives.",
  "Your precious empathy makes the world better.",
  "Your creative heart makes the world better.",
  "Your caring heart brings joy to others.",
  "Your unique heart is deeply appreciated.",
  "Your fierce heart makes the world better.",
  "Your unique heart is so comforting.",
  "Your unique perspective brings joy to others.",
  "Your bright spirit inspires people.",
  "Your warm empathy is a gift.",
  "Your brave laugh is a gift.",
  "Your kind laugh inspires people.",
  "Your courageous empathy inspires people.",
  "Your brave compassion is a gift.",
  "Your loved passion matters so much.",
  "Your thoughtful spirit is truly beautiful.",
  "Your beautiful perspective matters so much.",
  "Your funny smile is unforgettable.",
  "Your amazing compassion lights up the room.",
  "Your brilliant laugh makes the world better.",
  "Your valued energy changes lives.",
  "Your warm ideas matters so much.",
  "Your gentle presence lights up the room.",
  "Your unique presence is truly beautiful.",
  "Your loved heart is deeply appreciated.",
  "Your amazing ideas makes people happy.",
  "Your precious mind is deeply appreciated.",
  "Your courageous smile lights up the room.",
  "Your brilliant energy lights up the room.",
  "Your loved spirit is deeply appreciated.",
  "Your courageous empathy is truly beautiful.",
  "Your warm spirit makes people happy.",
  "Your valued smile lights up the room.",
  "Your amazing ideas is so comforting.",
  "Your warm heart makes the world better.",
  "Your sweet spirit is a gift.",
  "Your sweet perspective inspires people.",
  "Your gentle heart makes the world better.",
  "Your loved soul lights up the room.",
  "Your beautiful soul makes the world better.",
  "Your wonderful ideas matters so much.",
  "Your courageous smile matters so much.",
  "Your amazing compassion is so comforting.",
  "Your fierce heart is truly beautiful.",
  "Your creative perspective lights up the room.",
  "Your inspiring soul matters so much.",
  "Your caring heart changes lives.",
  "Your strong ideas is a gift.",
  "Your thoughtful energy makes people happy.",
  "Your resilient empathy makes people happy.",
  "Your beautiful ideas changes lives.",
  "Your smart ideas is deeply appreciated.",
  "Your amazing perspective is deeply appreciated.",
  "Your resilient presence is a gift.",
  "Your fierce compassion inspires people.",
  "Your amazing heart is a gift.",
  "Your beautiful presence changes lives.",
  "Your warm passion is truly beautiful.",
  "Your sweet ideas is a gift.",
  "Your loved mind is unforgettable.",
  "Your special laugh lights up the room.",
  "Your strong energy is deeply appreciated.",
  "Your caring empathy makes the world better.",
  "Your caring soul is unforgettable.",
  "Your precious passion is a gift.",
  "Your brave smile makes people happy.",
  "Your inspiring ideas inspires people.",
  "Your inspiring laugh is deeply appreciated.",
  "Your kind spirit brings joy to others.",
  "Your inspiring empathy is unforgettable.",
  "Your brilliant heart lights up the room.",
  "Your loved laugh is deeply appreciated.",
  "Your wonderful smile is a gift.",
  "Your bright mind is a gift.",
  "Your thoughtful compassion makes people happy.",
  "Your brave ideas inspires people.",
  "Your resilient heart inspires people.",
  "Your creative soul is so comforting.",
  "Your thoughtful spirit lights up the room.",
  "Your unique empathy is so comforting.",
  "Your gentle compassion brings joy to others.",
  "Your special soul lights up the room.",
  "Your precious heart is a gift.",
  "Your smart ideas lights up the room.",
  "Your courageous mind changes lives.",
  "Your loved passion is a gift."
];