// 200+ Tiny Wins organized by category
// Each win is an object with { text, category, emoji }
const masterWinsPool = [
  // === HYDRATION & NOURISHMENT ===
  { text: "Drank a full glass of water", category: "Hydration", emoji: "💧" },
  { text: "Ate a piece of fruit", category: "Nourishment", emoji: "🍎" },
  { text: "Had a proper breakfast", category: "Nourishment", emoji: "🥣" },
  { text: "Drank herbal tea", category: "Hydration", emoji: "🍵" },
  { text: "Ate a vegetable today", category: "Nourishment", emoji: "🥦" },
  { text: "Cooked something for myself", category: "Nourishment", emoji: "🍳" },
  { text: "Ate without scrolling my phone", category: "Mindfulness", emoji: "🧘" },
  { text: "Had a warm drink to relax", category: "Hydration", emoji: "☕" },
  { text: "Tried a new healthy snack", category: "Nourishment", emoji: "🥜" },
  { text: "Drank water first thing in the morning", category: "Hydration", emoji: "🌅" },

  // === MOVEMENT & BODY ===
  { text: "Stretched my body for 2 minutes", category: "Movement", emoji: "🤸" },
  { text: "Took a short walk outside", category: "Movement", emoji: "🚶" },
  { text: "Did 10 jumping jacks", category: "Movement", emoji: "⭐" },
  { text: "Danced to a song I love", category: "Movement", emoji: "💃" },
  { text: "Stood up and stretched between tasks", category: "Movement", emoji: "🧍" },
  { text: "Did a few yoga poses", category: "Movement", emoji: "🧘" },
  { text: "Rolled my shoulders and neck", category: "Movement", emoji: "🔄" },
  { text: "Took the stairs instead of the elevator", category: "Movement", emoji: "🪜" },
  { text: "Went outside for fresh air", category: "Movement", emoji: "🌿" },
  { text: "Wiggled my toes and appreciated my feet", category: "Movement", emoji: "🦶" },
  { text: "Did some deep squats", category: "Movement", emoji: "🏋️" },
  { text: "Played with a pet or stuffed animal", category: "Movement", emoji: "🐾" },

  // === MINDFULNESS & BREATHING ===
  { text: "Took three slow deep breaths", category: "Mindfulness", emoji: "🌬️" },
  { text: "Sat in silence for one minute", category: "Mindfulness", emoji: "🤫" },
  { text: "Noticed five things I could see", category: "Mindfulness", emoji: "👀" },
  { text: "Listened to calming sounds", category: "Mindfulness", emoji: "🎵" },
  { text: "Put my phone down for 15 minutes", category: "Mindfulness", emoji: "📵" },
  { text: "Watched clouds or rain for a moment", category: "Mindfulness", emoji: "☁️" },
  { text: "Closed my eyes and counted to ten", category: "Mindfulness", emoji: "🔟" },
  { text: "Focused on one task at a time", category: "Mindfulness", emoji: "🎯" },
  { text: "Meditated for even just one minute", category: "Mindfulness", emoji: "🧘" },
  { text: "Used the Breathing Bubble exercise", category: "Mindfulness", emoji: "🫧" },
  { text: "Listened to a guided meditation", category: "Mindfulness", emoji: "🎧" },
  { text: "Paused before reacting to something", category: "Mindfulness", emoji: "⏸️" },

  // === SELF-CARE & COMFORT ===
  { text: "Took a warm shower or bath", category: "Self-Care", emoji: "🛁" },
  { text: "Brushed my teeth", category: "Self-Care", emoji: "🪥" },
  { text: "Washed my face", category: "Self-Care", emoji: "🧼" },
  { text: "Put on clean clothes", category: "Self-Care", emoji: "👕" },
  { text: "Applied sunscreen or moisturizer", category: "Self-Care", emoji: "🧴" },
  { text: "Made my bed", category: "Self-Care", emoji: "🛏️" },
  { text: "Tidied up one small area", category: "Self-Care", emoji: "✨" },
  { text: "Lit a candle or incense", category: "Self-Care", emoji: "🕯️" },
  { text: "Wrapped myself in a cozy blanket", category: "Self-Care", emoji: "🧸" },
  { text: "Applied chapstick or hand cream", category: "Self-Care", emoji: "💅" },
  { text: "Wore something that makes me feel good", category: "Self-Care", emoji: "👗" },
  { text: "Hugged a pillow or stuffed animal", category: "Self-Care", emoji: "🤗" },

  // === KINDNESS & CONNECTION ===
  { text: "Smiled at someone", category: "Kindness", emoji: "😊" },
  { text: "Said something kind to a stranger", category: "Kindness", emoji: "💬" },
  { text: "Texted a friend to check in", category: "Connection", emoji: "📱" },
  { text: "Told someone I appreciate them", category: "Kindness", emoji: "💕" },
  { text: "Helped someone with a small task", category: "Kindness", emoji: "🤝" },
  { text: "Complimented someone genuinely", category: "Kindness", emoji: "⭐" },
  { text: "Listened to someone without interrupting", category: "Connection", emoji: "👂" },
  { text: "Sent a positive message to a loved one", category: "Connection", emoji: "💌" },
  { text: "Forgave someone (even a tiny bit)", category: "Kindness", emoji: "🕊️" },
  { text: "Said 'thank you' and really meant it", category: "Kindness", emoji: "🙏" },
  { text: "Let someone go ahead of me in line", category: "Kindness", emoji: "👋" },
  { text: "Shared something I had with someone", category: "Kindness", emoji: "🎁" },

  // === GRATITUDE & POSITIVITY ===
  { text: "Wrote down one thing I'm grateful for", category: "Gratitude", emoji: "📝" },
  { text: "Smiled at my own reflection", category: "Positivity", emoji: "🪞" },
  { text: "Said one nice thing about myself", category: "Positivity", emoji: "💛" },
  { text: "Noticed something beautiful around me", category: "Gratitude", emoji: "🌸" },
  { text: "Remembered a happy memory", category: "Positivity", emoji: "🌈" },
  { text: "Thought about someone I love", category: "Gratitude", emoji: "❤️" },
  { text: "Appreciated my body for carrying me today", category: "Gratitude", emoji: "💪" },
  { text: "Found humor in a small moment", category: "Positivity", emoji: "😂" },
  { text: "Listed three good things about today", category: "Gratitude", emoji: "✅" },
  { text: "Said 'I am enough' out loud", category: "Positivity", emoji: "🗣️" },
  { text: "Celebrated a small achievement", category: "Positivity", emoji: "🎉" },
  { text: "Accepted a compliment without deflecting", category: "Positivity", emoji: "☀️" },

  // === CREATIVITY & LEARNING ===
  { text: "Drew or doodled something", category: "Creativity", emoji: "🎨" },
  { text: "Wrote a few sentences in a journal", category: "Creativity", emoji: "📓" },
  { text: "Hummed or sang a song", category: "Creativity", emoji: "🎶" },
  { text: "Read a few pages of a book", category: "Learning", emoji: "📖" },
  { text: "Learned a new word", category: "Learning", emoji: "📚" },
  { text: "Watched something educational", category: "Learning", emoji: "🎬" },
  { text: "Tried a new creative hobby", category: "Creativity", emoji: "🖌️" },
  { text: "Wrote a poem or haiku", category: "Creativity", emoji: "✍️" },
  { text: "Played a musical instrument", category: "Creativity", emoji: "🎸" },
  { text: "Built something with my hands", category: "Creativity", emoji: "🔨" },
  { text: "Listened to a podcast", category: "Learning", emoji: "🎙️" },
  { text: "Took a photo of something interesting", category: "Creativity", emoji: "📸" },

  // === REST & BOUNDARIES ===
  { text: "Took a nap without guilt", category: "Rest", emoji: "😴" },
  { text: "Went to bed at a reasonable time", category: "Rest", emoji: "🌙" },
  { text: "Said 'no' to something I didn't want to do", category: "Boundaries", emoji: "🚫" },
  { text: "Rested when my body asked for it", category: "Rest", emoji: "💤" },
  { text: "Turned off notifications for a while", category: "Boundaries", emoji: "🔕" },
  { text: "Took a break from social media", category: "Boundaries", emoji: "📴" },
  { text: "Cancelled something that was draining me", category: "Boundaries", emoji: "🛑" },
  { text: "Let myself be lazy without guilt", category: "Rest", emoji: "🦥" },
  { text: "Set a screen time limit and respected it", category: "Boundaries", emoji: "⏰" },
  { text: "Removed myself from a stressful situation", category: "Boundaries", emoji: "🚪" },
  { text: "Asked for space when I needed it", category: "Boundaries", emoji: "🙌" },
  { text: "Prioritized my sleep over entertainment", category: "Rest", emoji: "🛌" },

  // === NATURE & ENVIRONMENT ===
  { text: "Stepped outside and felt the sun", category: "Nature", emoji: "☀️" },
  { text: "Looked at the sky for a full minute", category: "Nature", emoji: "🌤️" },
  { text: "Touched grass (literally)", category: "Nature", emoji: "🌱" },
  { text: "Watched a sunset or sunrise", category: "Nature", emoji: "🌅" },
  { text: "Smelled a flower", category: "Nature", emoji: "🌷" },
  { text: "Listened to birds singing", category: "Nature", emoji: "🐦" },
  { text: "Watered a plant", category: "Nature", emoji: "🪴" },
  { text: "Sat near a tree and felt calm", category: "Nature", emoji: "🌳" },
  { text: "Noticed the weather and appreciated it", category: "Nature", emoji: "🌦️" },
  { text: "Picked up a piece of litter", category: "Nature", emoji: "♻️" },
  { text: "Opened a window for fresh air", category: "Nature", emoji: "🪟" },
  { text: "Watched rain fall peacefully", category: "Nature", emoji: "🌧️" },

  // === EMOTIONAL WELLNESS ===
  { text: "Identified what I was feeling", category: "Emotional", emoji: "🧠" },
  { text: "Let myself feel an emotion fully", category: "Emotional", emoji: "💗" },
  { text: "Cried when I needed to", category: "Emotional", emoji: "😢" },
  { text: "Talked about my feelings with someone", category: "Emotional", emoji: "🗨️" },
  { text: "Forgave myself for a past mistake", category: "Emotional", emoji: "🕊️" },
  { text: "Acknowledged that I'm doing my best", category: "Emotional", emoji: "🌟" },
  { text: "Let go of something I can't control", category: "Emotional", emoji: "🎈" },
  { text: "Reminded myself that tough times are temporary", category: "Emotional", emoji: "⏳" },
  { text: "Validated my own feelings without judgment", category: "Emotional", emoji: "✨" },
  { text: "Chose compassion over criticism for myself", category: "Emotional", emoji: "🫂" },
  { text: "Recognized a negative thought and reframed it", category: "Emotional", emoji: "🔄" },
  { text: "Gave myself permission to not be perfect", category: "Emotional", emoji: "💫" },

  // === ORGANIZATION & PRODUCTIVITY ===
  { text: "Made a simple to-do list", category: "Organization", emoji: "📋" },
  { text: "Completed one small task I'd been avoiding", category: "Productivity", emoji: "✅" },
  { text: "Cleaned up my desk or workspace", category: "Organization", emoji: "🗄️" },
  { text: "Deleted old photos or files I don't need", category: "Organization", emoji: "🗑️" },
  { text: "Put something back where it belongs", category: "Organization", emoji: "📦" },
  { text: "Planned tomorrow before going to bed", category: "Organization", emoji: "📅" },
  { text: "Unsubscribed from an annoying email", category: "Organization", emoji: "📧" },
  { text: "Did the dishes", category: "Productivity", emoji: "🍽️" },
  { text: "Sorted through one pile of stuff", category: "Organization", emoji: "📁" },
  { text: "Spent 5 minutes decluttering", category: "Organization", emoji: "🧹" },
  { text: "Finished something I started yesterday", category: "Productivity", emoji: "🏁" },
  { text: "Replied to a message I'd been putting off", category: "Productivity", emoji: "💬" },

  // === FUN & PLAY ===
  { text: "Watched something that made me laugh", category: "Fun", emoji: "😆" },
  { text: "Played a game just for fun", category: "Fun", emoji: "🎮" },
  { text: "Made a silly face in the mirror", category: "Fun", emoji: "🤪" },
  { text: "Told or heard a joke", category: "Fun", emoji: "😄" },
  { text: "Did something spontaneous", category: "Fun", emoji: "🎲" },
  { text: "Watched cute animal videos", category: "Fun", emoji: "🐱" },
  { text: "Played Barnaby's Lost Dumplings", category: "Fun", emoji: "🥟" },
  { text: "Built something in my imagination", category: "Fun", emoji: "🏰" },
  { text: "Made a paper airplane", category: "Fun", emoji: "✈️" },
  { text: "Colored or painted something", category: "Fun", emoji: "🖍️" },
  { text: "Sang badly and loudly on purpose", category: "Fun", emoji: "🎤" },
  { text: "Tried a new recipe just because", category: "Fun", emoji: "👩‍🍳" },

  // === DIGITAL WELLNESS ===
  { text: "Unfollowed an account that made me feel bad", category: "Digital", emoji: "❌" },
  { text: "Used my phone for less than 2 hours", category: "Digital", emoji: "📱" },
  { text: "Didn't check my phone first thing in the morning", category: "Digital", emoji: "🌅" },
  { text: "Read an article instead of scrolling", category: "Digital", emoji: "📰" },
  { text: "Set my phone to Do Not Disturb", category: "Digital", emoji: "🔇" },
  { text: "Had a conversation without checking my phone", category: "Digital", emoji: "💬" },
  { text: "Cleaned up my phone's home screen", category: "Digital", emoji: "📲" },
  { text: "Spent time offline doing something enjoyable", category: "Digital", emoji: "🌿" },

  // === EXTRA WHOLESOME ===
  { text: "Existed today, and that's enough", category: "Self-Love", emoji: "🌸" },
  { text: "Survived a hard moment", category: "Self-Love", emoji: "🏆" },
  { text: "Chose hope over despair", category: "Self-Love", emoji: "🌈" },
  { text: "Showed up even when I didn't want to", category: "Self-Love", emoji: "🦁" },
  { text: "Was patient with myself", category: "Self-Love", emoji: "🕰️" },
  { text: "Remembered that I matter", category: "Self-Love", emoji: "💎" },
  { text: "Let go of comparison", category: "Self-Love", emoji: "🪞" },
  { text: "Trusted the process", category: "Self-Love", emoji: "🌱" },
  { text: "Showed courage in a small way", category: "Self-Love", emoji: "🦋" },
  { text: "Admitted I needed help", category: "Self-Love", emoji: "🤲" },
  { text: "Started something new despite fear", category: "Self-Love", emoji: "🚀" },
  { text: "Believed in myself for even one second", category: "Self-Love", emoji: "⭐" }
];

module.exports = masterWinsPool;
